import type { Article } from './article-types'

/** Replaces removed city guides + World Cup piece. */
export const REPLACED_ARTICLE_SLUGS = new Set([
  'music-world-cup-2026-texas',
  'austin-music-scene-2026',
  'houston-rap-scene-rising-2026',
  'san-antonio-live-music-guide-2026',
  'dallas-concert-culture-2026',
])

export const cityAndYeArticles: Article[] = [
  {
    slug: 'ye-alamodome-july-4-2026',
    type: 'preview',
    title: "Ye at the Alamodome on the Fourth of July: What to Know Before America's 250th Birthday Gets Loud",
    subtitle:
      'More than 50,000 fans are expected for one of the largest concerts in Alamodome history — on the holiday weekend, in a room that has been on a historic run.',
    author: 'Diego Jauregui',
    date: '2026-07-02',
    displayDate: 'July 2, 2026',
    category: 'Show Preview',
    venue: 'Alamodome',
    coverIndex: 0,
    heroImage: '/articles/ye-alamodome-july-4-2026/ye-alamodome-hero.png',
    readTime: '7 min read',
    body: [
      "Ye — the artist formerly known as Kanye West — is playing the Alamodome on **Friday, July 4, 2026**. That is two days from now. The show lands on America's 250th birthday, in a building that has spent the last eighteen months on one of the busiest concert runs in its history. City officials expect **more than 50,000 fans** inside the dome, which would put this among the highest-attended musical events the venue has ever hosted.",
      "The announcement came fast. Pre-sale tickets ran **10 a.m. to 10 p.m. on Thursday, June 18**; general public sales opened **10 a.m. Friday, June 19**. If you are reading this with a ticket already in hand, the useful part starts below. If you are still trying to get in, resale is the only lane left — and it will not be cheap.",
      "## Why this show is as big as the numbers suggest",
      "San Antonio's Alamodome attendance records for concerts still start with **George Strait at 70,956** (June 1, 2013). The top of the board after that: **Bad Bunny at 54,000** (September 7, 2022), a Strait / Reba / LeAnn Rimes bill at **53,899**, **One Direction at 48,942**, and **Paul McCartney at 48,709**. Bad Bunny also holds the gross record — more than **$11 million** on that 2022 run.",
      "Recent headliners have kept the room hot: **The Weeknd** (48,511), **Billy Joel and Sting** (47,288), **Paul McCartney** again (44,600), **Red Hot Chili Peppers** (43,189), **Chris Brown** (43,000), **Luke Combs** (42,190), **Shakira** (41,441), and **Post Malone with Jelly Roll** (41,071). Ye's team clearly understood the market — San Antonio, northern Mexico, and the broader South Texas corridor buy arena shows without needing a long turnaround. Richard Oliver, communications manager for the City of San Antonio, put it plainly to local press: promoters know this audience will show up on a holiday weekend.",
      "Fall is already stacked at the dome — **AC/DC**, **Bruno Mars**, **Karol G**, and **My Chemical Romance** are on the books. But between now and early October, city staff have said this stretch may be the busiest concert window in Alamodome history. Ye on the Fourth is the exclamation point at the front of that timeline.",
      "[PHOTOS:/articles/ye-alamodome-july-4-2026/ye-alamodome-inline.jpg|Ye's live production has always operated at arena scale — San Antonio gets the full version on the Fourth.]",
      "## Know before you go",
      "**Date & doors:** Friday, **July 4, 2026**. Exact door and set times have not been finalized as of publication — check your ticket confirmation and the Alamodome social accounts the day of the show. Plan to be in the footprint early. A 50,000-capacity holiday show does not reward late arrivals.",
      "**Merch:** Official merchandise sales open **Thursday, July 3, from 12 p.m. to 6 p.m.** outside the venue. If you want a specific size or item without fighting the concourse rush on show night, that window is your move.",
      "**Parking & arrival:** The Alamodome sits just east of downtown with multiple paid lots and garage options. Expect heavy traffic on I-35, I-10, and surface streets all afternoon and evening — it is the Fourth, the show is national news, and everyone with a ticket is arriving at the same time. Rideshare pickup zones fill fast after the encore; if you are splitting a ride, agree on a meeting spot before the headliner starts.",
      "**What to bring:** Clear-bag policies and security screening are standard at the Alamodome. Travel light — phone, ID, payment, earplugs if you want them. Leave anything you do not need at home and read the venue's posted bag policy before you leave.",
      "**Heat & hydration:** Early July in San Antonio is real. Even with indoor AC, the walk in, the lot, and the merch line outside will be hot. Water before you go in; do not skip it because you are rushing to your seat.",
      "**The holiday factor:** This is not a normal Friday show. Fireworks, family plans, and citywide events all compete for the same roads and the same parking. Build buffer time you would not need on a random Tuesday arena date.",
      "## What to expect from the performance",
      "Ye's live production has always been the point as much as the setlist. The floating-stage, arena-scale visual language from recent tours — the suspended platform, the red wash, the crowd shot from above looking like a single organism — is the template. San Antonio is getting the stadium version of that idea inside the dome.",
      "Setlist speculation is useless until the first note, but the catalog depth is obvious: **The College Dropout** through **Donda** and everything in between, plus the production detours that turn a hip-hop show into something closer to performance art. If you have seen Ye live before, you know the show rarely stays predictable. If you have not, this is the room to see it in — big enough to feel like an event, still contained enough that you are not watching from a football-field away.",
      "## The bottom line",
      "America's 250th birthday. San Antonio. One of the largest crowds the Alamodome has ever held for a single artist. Ye has always treated the live stage like a canvas — this is the weekend that canvas gets the whole city watching.",
      "We will be there. Show tips and post-show coverage to follow.",
      "[TICKETS]",
    ],
    tags: [
      'Ye',
      'Kanye West',
      'Alamodome',
      'San Antonio',
      'Fourth of July',
      'Show Preview',
      'Hip-Hop/Rap',
    ],
  },
  {
    slug: 'san-antonio-venues-guide',
    type: 'spotlight',
    title: 'San Antonio Venues: Every Room Worth Knowing',
    subtitle:
      'From the Alamodome to the Saint Mary\'s strip — capacity, genre, and what\'s coming up at each room.',
    author: 'Diego Jauregui',
    date: '2026-07-01',
    displayDate: 'July 1, 2026',
    category: 'City Guide',
    venue: 'San Antonio, TX',
    coverIndex: 4,
    heroImage: '/articles/san-antonio-venues-guide/cover.png',
    readTime: '8 min read',
    body: [
      "San Antonio's live music infrastructure is better than its reputation. The city has an arena, a restored downtown theater circuit, and a strip of rooms on North Saint Mary's that function as a single neighborhood scene. Below is every venue we track for small-to-large touring — what each room usually books, and **upcoming shows pulled live from Ticketmaster** (refreshed hourly).",
      "[CITY_VENUES:San Antonio]",
      "The Saint Mary's strip is still where the scene lives on a weeknight: Paper Tiger, Hi-Tones, Lonesome Rose, and the bars between them. For arena scale, the Alamodome and Frost Bank Center split the biggest routing in town. If a show is not listed under a venue yet, check the full calendar — announcements land daily during busy seasons.",
    ],
    tags: ['San Antonio', 'City Guide', 'Venues', 'Paper Tiger', 'Aztec Theatre', 'Alamodome', 'Live Music'],
  },
  {
    slug: 'austin-venues-guide',
    type: 'spotlight',
    title: 'Austin Venues: Every Room Worth Knowing',
    subtitle:
      'From Red River clubs to the Moody Center — capacity, genre, and live listings across the Live Music Capital.',
    author: 'Diego Jauregui',
    date: '2026-06-28',
    displayDate: 'June 28, 2026',
    category: 'City Guide',
    venue: 'Austin, TX',
    coverIndex: 2,
    heroImage: '/articles/austin-venues-guide/cover.png',
    readTime: '8 min read',
    body: [
      "Austin still earns the Live Music Capital title on volume alone — Stubb's, Mohawk, Emo's, ACL Live, and the Red River corridor run seven nights a week while the Moody Center and Germania Amphitheater handle arena and shed routing. This guide lists every room we track from club to arena, what each usually books, and **upcoming shows pulled live from Ticketmaster** (refreshed hourly).",
      "[CITY_VENUES:Austin]",
      "Red River is still where the weeknight scene lives — Mohawk, Parish, Empire, and the bars between them. For ACL season in October, Zilker is a separate conversation (we have festival previews on the site). If a room shows no listings yet, check the calendar — Austin announcements move fast during festival season and summer shed routing.",
    ],
    tags: ['Austin', 'City Guide', 'Venues', 'Mohawk', "Stubb's", 'ACL Live', 'Red River', 'Live Music'],
  },
  {
    slug: 'houston-venues-guide',
    type: 'spotlight',
    title: 'Houston Venues: Every Room Worth Knowing',
    subtitle:
      'Toyota Center to White Oak — the rooms that run Houston\'s calendar, what they book, and what\'s on sale now.',
    author: 'Diego Jauregui',
    date: '2026-06-30',
    displayDate: 'June 30, 2026',
    category: 'City Guide',
    venue: 'Houston, TX',
    coverIndex: 7,
    heroImage: '/articles/houston-venues-guide/cover.png',
    readTime: '8 min read',
    body: [
      "Houston has the deepest rap live infrastructure in Texas and one of the strongest overall concert economies in the country. Arena shows at Toyota Center, mid-tier rooms like 713 Music Hall and White Oak, and the club circuit that never stops — the city runs all of it at once. This guide lists the venues we watch, the genres each room usually carries, and **live upcoming listings** updated from Ticketmaster every hour.",
      "[CITY_VENUES:Houston]",
      "Houston's calendar moves fast. If a room shows nothing listed today, that usually means the next announcement has not hit Ticketmaster yet — not that the room is dark. Use the calendar city filter for the full metro slate.",
    ],
    tags: ['Houston', 'City Guide', 'Venues', '713 Music Hall', 'White Oak Music Hall', 'Toyota Center', 'Live Music'],
  },
  {
    slug: 'dallas-venues-guide',
    type: 'spotlight',
    title: 'Dallas–Fort Worth Venues: Every Room Worth Knowing',
    subtitle:
      'Deep Ellum clubs, Irving sheds, Arlington stadiums — capacity, genre, and current listings across the metro.',
    author: 'Diego Jauregui',
    date: '2026-06-29',
    displayDate: 'June 29, 2026',
    category: 'City Guide',
    venue: 'Dallas-Fort Worth',
    coverIndex: 1,
    heroImage: '/articles/dallas-venues-guide/cover.png',
    readTime: '8 min read',
    body: [
      "Dallas-Fort Worth has the largest live music economy in Texas by capacity and revenue. Deep Ellum still anchors the independent scene — Granada, Trees, The Factory — while American Airlines Center, Dos Equis Pavilion, and Toyota Music Factory handle everything from arena pop to shed season. This guide covers the rooms from club to stadium, what each one usually books, and **upcoming shows synced hourly** from Ticketmaster across the metro.",
      "[CITY_VENUES:Dallas]",
      "DFW spans multiple cities on the calendar — Irving, Arlington, and Fort Worth listings count here. Filter by Dallas on the calendar page for everything in one list.",
    ],
    tags: ['Dallas', 'Deep Ellum', 'City Guide', 'Venues', 'Granada Theater', 'American Airlines Center', 'Live Music'],
  },
]
