import type { Article, RadarEntry } from './article-types'
import { cityAndYeArticles, REPLACED_ARTICLE_SLUGS } from './articles-city-ye'
import { showRecapArticles } from './articles-show-recaps'

export type { Article, RadarEntry } from './article-types'

const legacyArticles: Article[] = [
  {
    slug: 'acl-2026-preview-texas-acts',
    type: 'preview',
    title: 'ACL 2026 Preview: The Texas Acts Worth Showing Up Early For',
    subtitle:
      'Six homegrown artists buried in the undercard who could steal the festival before the headliners hit the stage.',
    author: 'Diego Jauregui',
    date: '2026-05-22',
    displayDate: 'May 22, 2026',
    category: 'Festival Preview',
    venue: 'Zilker Park, Austin',
    coverIndex: 3,
    readTime: '5 min read',
    body: [
      "The 2026 Austin City Limits lineup dropped earlier this month, and as is tradition, the conversation went immediately to the headliners. That's how festivals work — the names at the top of the poster do the press cycle, sell the tickets, and frame the story. But the bigger story this year is happening lower on the bill, where Texas artists are stacked across the four days in a way ACL hasn't programmed in years.",
      "The names are smaller, the set times are mid-afternoon, and the press cycle hasn't bothered to flag them yet. But anyone watching the Texas scene over the last twelve months should already have a few of these acts circled. ACL has always been about more than its headliners — the festival has been a launching pad for regional artists since **C3 Presents** started running it at Zilker Park in 2002, and the 2026 booking might be the strongest case for that model in a decade.",
      "## Who's worth getting there early for",
      "The Texas presence cuts across genre and city. A Houston rapper coming off her best year ever and a major-label rollout that's expected to peak right around festival weekend. An Austin indie band whose debut album landed harder than anyone expected and is reportedly already cutting their sophomore record. A San Antonio-rooted R&B project that's been quietly opening for everyone — including two arena tours we tracked through Texas this spring. A Dallas production duo whose late-2025 mixtape is going to age into a regional classic, and whose first ACL booking lands them on one of the festival's main stages during golden hour on Saturday.",
      "None of them are headlining. All of them are worth showing up for. The right move with ACL has always been to build your weekend around the smaller-stage discoveries and let the headliners be whatever they're going to be. This year, that math is more obvious than usual.",
      "## Why this lineup feels different",
      "ACL has historically been weighted toward national bookings. Local programming has been there but light, often pushed to the smaller stages on Sunday afternoon when half the crowd is already cooked from two days of sun. The result was a festival that lived in Austin but didn't really sound like it.",
      "This year reads different. Whether that's intentional curation or a reflection of how much Texas music has shifted is impossible to say from outside. The state's hip-hop output has exploded since 2023. Houston is producing more relevant names than at any point since the screw era. Dallas has the most active independent scene it's had since the late 2000s. San Antonio is exporting artists for the first time in a decade. ACL would have to be deliberately ignoring all of that to not reflect it — and the 2026 schedule suggests they're done ignoring it.",
      "## How to actually plan your weekend",
      "The trap with ACL is the headliner FOMO. People plan their day around 9 PM closers and miss everything that mattered. The Texas slots this year are concentrated in the 2 PM - 6 PM window across all four festival days. Get to Zilker by lunch, do the rounds, and you'll see the festival most people are going to miss.",
      "Both weekends are running the same lineup. Weekend One sells out faster and has more energy on day one. Weekend Two has better crowd density, shorter food lines, and slightly cooler weather. If you're flexible, Weekend Two is the better experience for the same lineup. If you can't be flexible — get tickets, get there early, build the day around the under-card.",
      "[NOTE] Full lineup and set times at aclfestival.com. We'll have on-the-ground coverage from both weekends — show tips and recommendations welcome via the contact page.",
    ],
    tags: [
      'ACL Festival',
      'Austin',
      'Festival Preview',
      'Texas Music',
      'Live Music',
      '2026',
    ],
  },
  {
    slug: 'acl-festival-2026-full-preview',
    type: 'preview',
    title: 'ACL 2026: The Complete Preview',
    subtitle:
      "Two weekends. Eight stages. A quarter-million people. The biggest music event in Texas every year is back — here's the lineup, the layout, and how to actually do it.",
    author: 'Diego Jauregui',
    date: '2026-05-21',
    displayDate: 'May 21, 2026',
    category: 'Festival Preview',
    venue: 'Zilker Park, Austin',
    coverIndex: 2,
    readTime: '7 min read',
    body: [
      "Austin City Limits is the biggest music event in Texas every year, and one of the most important festivals in the country period. The festival takes over Zilker Park for two weekends in early October — six days of music across eight stages, a quarter-million attendees total across both weekends, and a lineup that's run from Paul Simon to Tyler, The Creator to Kendrick Lamar without losing its identity along the way. The 2026 edition is the festival's twenty-fourth year, and based on the lineup **C3 Presents** announced earlier this month, it might be one of the strongest of the recent run.",
      "## What ACL actually is",
      "ACL was launched in 2002 by C3 Presents, an Austin-based promotion company that has since become one of the largest concert promoters in the world. The festival shares a name with the long-running **Austin City Limits** television show — the PBS music program that's been broadcasting from Austin since 1974 — but the festival and the show are now separately operated, with the festival functioning as the larger-scale commercial sibling to the show's smaller, more focused taping format.",
      "The festival runs across both weekends of early October every year — this year, October 2-4 and October 9-11. The same lineup plays both weekends, with a handful of artist-specific exceptions. Weekend One sells out faster and gets the bigger press cycle. Weekend Two has better crowd density, shorter food lines, and slightly cooler weather. If you have the flexibility, Weekend Two is the better experience.",
      "## The 2026 lineup",
      "The 2026 headliners have not been universally well-received — the social media reception was the usual mix of complaints about repeat bookings and complaints about not enough rap, country, or whatever the complainer's preferred genre is. That's how festival announcements work. The bill is deeper than the headliner conversation suggests, and the mid-card programming this year is unusually strong. (We have a separate piece on the Texas acts buried in the under-card — worth reading if you're planning your schedule.)",
      "Genre-wise, the festival continues its slow shift toward broader programming. The 2022-2024 lineups leaned heavier on hip-hop than the festival's first decade did, and the 2026 edition continues that trend without abandoning the indie rock and singer-songwriter identity the festival was originally known for. The Latin programming has gotten genuinely strong over the last three years, and the country and Americana stages are doing some of the festival's most interesting booking — even relative to Austin's broader music identity.",
      "## What to expect on the ground",
      "Eight stages, all running in parallel, all weekend long. The flagship stages — the American Express stage at the south end of the field, the Honda stage at the north end — host the biggest acts. The mid-tier stages host the mid-card. The smaller stages, especially the Tito's Stage and the BMI Stage, are where the festival's discovery moments happen.",
      "Set times are aggressive. There's almost always a conflict between two acts you want to see, and the festival's geography means moving between stages takes ten to fifteen minutes if the crowds are heavy. Plan the day, accept that you'll miss things, and stay flexible.",
      "## Tips for attending",
      "The basics: hydrate, eat enough food, wear sunscreen, and accept that Austin weather in early October is unpredictable. Some years are 95 degrees. Some years are 65 and pouring. Dress in layers.",
      "Get to Zilker before noon. The line at the gates after 1 PM is significantly worse than the early-morning line, and the mid-afternoon discovery acts are some of the festival's best programming. The early hours are also when the food trucks are at their best — by 8 PM the lines are 45 minutes, and the most popular vendors are often sold out.",
      "Cash bars are gone — the festival is fully cashless. Bring sealed water, but accept that you'll be refilling at the free water stations all day. Sunscreen and a hat will save your weekend. A small backpack that meets the festival's size restrictions (check the website for current rules) is worth the effort.",
      "The transportation situation is the trickiest part. Parking around Zilker is impossible. The festival offers shuttle service from satellite lots, the city has occasionally run a temporary rail line for the event, and ride-share gets brutal at peak hours. The smartest move is to stay downtown, take the festival shuttle in, and walk back across the bridge after closeout.",
      "## Why ACL still matters",
      "In a year when festivals across the country are folding, downsizing, or pivoting to electronic-music-only formats, ACL's continued scale and curatorial range stands out. The festival has stayed financially viable, programmed both legacy and emerging acts, and never compromised on its Austin identity even as the city's gotten bigger and the festival's gotten more national. C3's operational discipline is part of that. The city's investment in Zilker Park and the surrounding infrastructure is part of it. The festival's audience — generally a slightly older, more committed concert-going crowd than the EDM-heavy peer festivals — is the rest.",
      "ACL is the biggest music event in Texas. It's also one of the biggest in the country. Six days, two weekends, 250,000 people. The city of Austin doesn't really pause for it — it just absorbs it. That's the trick.",
      "[NOTE] Full lineup and set times at aclfestival.com. Weekend One: October 2-4. Weekend Two: October 9-11. We'll have full on-the-ground coverage from both weekends — daily wrap-ups, photo coverage, and post-festival recaps.",
    ],
    tags: [
      'ACL Festival',
      'Austin',
      'Festival Preview',
      'C3 Presents',
      'Zilker Park',
      'Live Music',
      '2026',
    ],
  },
  {
    slug: 'texas-artists-to-watch-all-genres-2026',
    type: 'spotlight',
    title: 'The Texas Artists to Watch in 2026 — Across Every Genre',
    subtitle:
      "Country, rap, R&B, indie, Latin alternative, electronic. The depth of the state's output across every scene at once is the real story of Texas music this year.",
    author: 'Diego Jauregui',
    date: '2026-05-19',
    displayDate: 'May 19, 2026',
    category: 'Artist Roundup',
    coverIndex: 4,
    readTime: '6 min read',
    body: [
      "The Texas music scene in 2026 has more depth across more genres than at any point in the last decade. The rap conversation is its own lane, but the bigger story — the one that doesn't get the press attention — is how broad the state's output has become. Indie, R&B, country and Americana, Latin alternative, electronic, jazz — there are working artists from Texas right now doing some of the most adventurous work in their respective lanes, and the names below should be on your radar through the rest of the year.",
      "This isn't a comprehensive list. It's a snapshot of the artists whose 2026 trajectories we're tracking most closely — the ones whose moves are likely to define how Texas music is remembered when this year is over.",
      "## The country and Americana lane",
      "Texas country has been having a generational moment for three years running now. **Charley Crockett** continues to be one of the most prolific working musicians in the genre — his release pace borders on absurd, and the catalog is consistently strong. The newer wave of Texas country — artists working out of the Hill Country corridor between Austin and San Antonio, releasing on independent labels and touring relentlessly — is producing some of the most respected roots music in America right now. The contrast with the Nashville mainstream couldn't be more visible. Where Nashville continues to over-polish and over-produce, the Texas independent country scene is doing the opposite — sparser, more honest, more interested in songwriting than in radio format.",
      "## The R&B and soul wave",
      "**Black Pumas** remain one of the most influential current soul acts from Texas, working out of Austin and pushing the genre into territory that hasn't been touched since the early seventies. **Leon Bridges**, from Fort Worth, continues to release records that get critical attention and Grammy nominations in roughly equal measure. **Bobby Sessions** out of Dallas operates more in the rap-and-R&B borderlands but the soul side of his output deserves more attention than it gets. The under-card includes a generation of younger R&B artists working out of Houston and Dallas whose names will be familiar to people inside the scene and obscure to everyone else — that gap is about to close.",
      "## The indie and rock contingent",
      "**Spoon**, still operating out of Austin, remains one of the most respected indie rock bands in the country after three decades of active touring. **White Denim**, also Austin, continues to release records that quietly outperform their press cycle. **Khruangbin**, technically Houston, has built an international following on the strength of a deeply specific instrumental aesthetic nobody else is doing. The state's indie output has shifted somewhat away from the rock identity that defined the 2000s and 2010s in favor of more electronic, more genre-fluid releases, but the foundational scene is still there.",
      "## The Latin alternative wave",
      "This is where the most growth has been. Texas's Latin alternative scene — broadly, the artists working in the space between regional Mexican, cumbia, indie rock, and pop — has been ascendant since 2022. Artists working out of San Antonio, Houston, and Austin are releasing some of the most adventurous bilingual music in America right now, and the festival circuit has finally caught up to the audience that's been there all along. Expect the second half of 2026 to produce a breakout act from this scene that ends up on national playlists by the end of the year.",
      "## The electronic and experimental edge",
      "Austin and Houston both have working electronic scenes that operate mostly outside the festival circuit. The kind of work being done in warehouse spaces and small clubs in both cities — ambient, drone, IDM, experimental dance — has been growing in scale for years, and the international touring presence of artists associated with both cities is the highest it's been in a decade. The crossover into hip-hop production has been the most visible result of the scene's growth.",
      "## The producer class",
      "The most underrated part of the Texas music conversation is the production work. The state has produced some of the most respected hip-hop and pop producers of the last thirty years — **Mike Dean** out of Houston, the production lineages of the screw era, the current generation of beat-makers working out of Dallas — and the producer-as-artist model continues to thrive across the state. Expect at least one Texas-affiliated producer to land a Billboard top-ten production credit by Q3.",
      "## What's actually new",
      "What separates 2026 from any previous year isn't the existence of any one of these scenes — it's the simultaneous strength of all of them. Texas has historically had strong moments in country, in rap, in R&B, in indie rock individually. In 2026, all five are running at full strength simultaneously. That hasn't been true in this state since the early seventies, when the cosmic-country, outlaw-country, and Houston rap origins were all converging in real time.",
      "Watch the names above. Watch the names we haven't gotten to yet. Texas music in 2026 has more entry points than at any point in living memory. Pick one and start there.",
    ],
    tags: [
      'Texas Music',
      'Artist Roundup',
      'Country',
      'R&B',
      'Indie',
      'Latin Alternative',
      'Electronic',
      'Spoon',
      'Black Pumas',
      'Charley Crockett',
      'Leon Bridges',
      '2026',
    ],
  },
  {
    slug: 'texas-summer-concert-guide-2026',
    type: 'preview',
    title: 'Your Texas Summer Concert Guide: The Shows Worth Marking Down',
    subtitle:
      "From outdoor amphitheaters in Austin to club dates on the Saint Mary's strip, here's where the energy is going to be.",
    author: 'Diego Jauregui',
    date: '2026-05-18',
    displayDate: 'May 18, 2026',
    category: 'Show Guide',
    coverIndex: 2,
    readTime: '6 min read',
    body: [
      "Summer in Texas is brutal, but the concert calendar makes up for it. Between the outdoor amphitheaters running their gates open until midnight, the indoor venues running their AC on max, and the festival circuit moving through Austin and Houston, the next four months are going to be unrelenting. We've been working through promoter announcements all spring — here's what we're marking down, city by city, and where we think the energy is going to be.",
      "## San Antonio",
      "**Paper Tiger** continues to do most of the heavy lifting for SA's underground bookings — three or four shows worth flying in for already on the books through August. The 1,200-cap room on the Saint Mary's strip has built a reputation for catching artists right before they outgrow rooms this size, and the summer lineup follows the pattern.",
      "**The Aztec Theatre**'s run of touring rap dates is also unusually deep this year. After the Freddie Dredd / Back to Hell stop in May, the Aztec is hosting a series of mid-level hip-hop and alternative bookings that would have routed past San Antonio entirely two years ago. **The Tobin Center** and **Majestic Theatre** are running their usual mix of theater-scale tours, jazz and Latin programming, and one-night-only specials — the Majestic's summer slate in particular is worth a full look. The **Frost Bank Center** has a handful of arena dates worth marking this summer.",
      "Don't sleep on **Sam's Burger Joint** and **The Lonesome Rose** for smaller bills. The Lonesome Rose's outdoor patio is the best low-key summer move in the city, and Sam's is one of the only rooms in town doing consistent under-21 booking.",
      "## Austin",
      "**Stubb's**, **Mohawk**, **Empire**, **ACL Live at the Moody Theater** — the rotation is on its normal cycle, with Stubb's outdoor amphitheater taking the bulk of the touring stops. **Antone's** continues its decades-long run as the city's blues home base, and **Emo's** has the most reliable mid-tier hip-hop and alternative calendar of any room in the city.",
      "The bigger story is the festival circuit. **ACL** in October is the obvious headliner (we have a full preview on this site). But the run of smaller festivals in June and July — **Hot Luck** on the food-and-music side, **Float Fest**, and the various one-day showcase events — are doing some of the more interesting booking this year. Watch the smaller bills.",
      "## Houston",
      "**White Oak Music Hall** is having its strongest summer in years. The newer **713 Music Hall** has filled a gap in the 2,500-3,000 cap range the city was missing. **Toyota Center** is hosting two of the bigger Texas-tied tours and a handful of national stops worth crossing the state for, and **NRG Stadium** has a stadium-level show or two on the books in addition to the **World Cup** matches in June and July.",
      "Houston's smaller rooms — **The Heights Theater**, **Continental Club** Houston, the various warehouse-district pop-ups — are also worth tracking. Houston has more rap shows per capita than any city in Texas, and most of them never make it onto the national booking radar.",
      "## Dallas-Fort Worth",
      "**Granada Theater** is the consistent flagship for Deep Ellum bookings. **The Factory in Deep Ellum** is doing the bigger touring stops. **House of Blues Dallas** and **South Side Music Hall** round out the mid-tier. **American Airlines Center** has a handful of arena dates that will move tickets fast. **AT&T Stadium** is going to be dominated by the World Cup through July, but the surrounding bookings — at smaller rooms and across Deep Ellum — are going to benefit from the international foot traffic.",
      "**Trees** in Deep Ellum continues to be the room where the city's harder-to-categorize bookings end up — punk, hardcore, experimental electronic, niche hip-hop. If you want to see what Dallas's actual scene looks like, the Trees calendar is where you start.",
      "## What we're tracking",
      "We'll keep this updated through Labor Day. New show announcements get added as confirmations come in, and we'll flag the ones we're going to be at with photo and review coverage. Show tips welcome at the contact page — promoters, publicists, and fans all get the same response window.",
      "Summer's already started. The shows aren't waiting on you.",
    ],
    tags: [
      'Texas Music',
      'Summer 2026',
      'Show Guide',
      'San Antonio',
      'Austin',
      'Houston',
      'Dallas',
    ],
  },
  {
    slug: 'freddie-dredd-back-to-hell-aztec-may-2026',
    type: 'review',
    title: "Freddie Dredd Brings the Back to Hell Tour to San Antonio's Aztec Theatre",
    subtitle:
      'Surprise Texas opener, four genuine sets at the intimate Aztec, and a headliner who held the room from first song to last.',
    author: 'Diego Jauregui',
    date: '2026-05-01',
    displayDate: 'May 1, 2026',
    category: 'Concert Review',
    venue: 'Aztec Theatre',
    coverIndex: 5,
    heroImage: '/articles/freddie-dredd-back-to-hell-aztec-may-2026/freddie-dredd-hero-dsc5420.png',
    readTime: '6 min read',
    body: [
      "The Back to Hell Tour made its San Antonio stop at the Aztec Theatre on May 1st, and what was already shaping up to be a great night of live music turned into something even better. The original bill listed **Germ** and one other opener alongside headliner **Freddie Dredd** — but the night came with a surprise addition in the form of a local Texas rapper who nobody saw coming. The crowd's reaction said it all. By the end of his set, fans were asking who he was, and the buzz around him carried all the way through the rest of the night.",
      "For anyone unfamiliar: Freddie Dredd has spent the last six years carving out one of the more singular lanes in modern rap. His catalog leans heavy on chopped, distorted, lo-fi production — closer in feel to the Memphis underground tradition of DJ Spanish Fly and Tommy Wright III than to anything happening on contemporary radio. He came up in close orbit with the **G*59** community and the broader **$uicideboy$** ecosystem, and his crossover to bigger rooms has been slow, quiet, and almost entirely fan-driven. The Aztec stop was the closest thing he's done to a proper Texas headline run in years.",
      "[PHOTOS:/articles/freddie-dredd-back-to-hell-aztec-may-2026/germ-1.png|Germ holds the Aztec Theatre crowd during his Back to Hell Tour set;;/articles/freddie-dredd-back-to-hell-aztec-may-2026/germ-2.png|Germ raises the mic mid-song under the Aztec Theatre's stage lights]",
      "## The room",
      "The Aztec Theatre seats about 1,800, and at capacity it's one of the more flattering rooms for rap shows in the state. The sightlines are tight, the sound system has held up well since the most recent renovation, and the balcony lets you see the entire floor without losing the energy of the pit. It's an old vaudeville house — built in 1926, restored, refurbished, and now one of the most consistently booked mid-sized rooms in San Antonio. For a tour like this one, the room is almost too dignified, and that contrast is part of why the night worked.",
      "All four performers brought something genuine to the stage. The intimate setting of the Aztec Theatre worked in everyone's favor — there's no smoke beyond the standard stage hazer, no pyrotechnics, no massive production, but there doesn't need to be. The energy in the room filled every gap. One artist jumped down from the stage into the pit mid-performance, grabbing fans' phones to record himself while the crowd lost it. Another connected with the audience between songs, taking time for real dialogue rather than just running through a setlist. The DJs held everything together seamlessly throughout the night.",
      "[PHOTOS:/articles/freddie-dredd-back-to-hell-aztec-may-2026/freddie-dredd-2.png|Freddie Dredd performs through stage smoke at the Aztec Theatre;;/articles/freddie-dredd-back-to-hell-aztec-may-2026/freddie-dredd-4.png|Freddie Dredd locked in under deep red light at the Aztec Theatre, San Antonio]",
      "## The openers",
      "**Germ** — a longtime $uicideboy$ collaborator and one of the more underrated voices in the broader G*59 catalog — handled the second-to-last slot like a veteran. His material translates better live than on record, and his half-screamed, melodic delivery cuts through the room in a way the studio mixes don't fully capture. He's been touring this material for nearly a year, and the polish is visible.",
      "[PHOTOS:/articles/freddie-dredd-back-to-hell-aztec-may-2026/germ-3.png|Germ delivers a verse close-up at the Aztec Theatre;;/articles/freddie-dredd-back-to-hell-aztec-may-2026/germ-4.png|Germ closes out his opening set on the Back to Hell Tour]",
      "## The headliner",
      "**Freddie Dredd** closed the night the way a headliner should — commanding the room and keeping the energy locked in from the first song to the last. The setlist drew heavily from the recent **Back to Hell** rollout, with a few deep cuts that triggered the crowd's biggest reactions of the night. His stage presence is understated — minimal pacing, no extended monologues, no encore theater — but the result is that the music does what the music is supposed to do. You watch a Freddie Dredd set and you remember the songs, not the show. That's a compliment.",
      "If you're a fan of **$uicideboy$** or that pocket of dark rap, this tour is worth every penny. Tickets are affordable, the shows are intimate, and the performances deliver. StagePulse recommends catching the Back to Hell Tour if it's coming to your city.",
      "[PHOTOS:/articles/freddie-dredd-back-to-hell-aztec-may-2026/freddie-dredd-1.png|Freddie Dredd commands the Aztec Theatre stage during his Back to Hell Tour headlining set;;/articles/freddie-dredd-back-to-hell-aztec-may-2026/freddie-dredd-cover.png|Freddie Dredd close-up under the Aztec Theatre's stage lights]",
    ],
    tags: [
      'Freddie Dredd',
      'Germ',
      'Aztec Theatre',
      'San Antonio',
      'Back to Hell Tour',
      'Concert Review',
      '$uicideboy$',
      'G*59',
    ],
  },
  {
    slug: 'rolling-loud-california-2026-recap',
    type: 'review',
    title: 'Rolling Loud California 2026 Recap: Three Days, One Hell of a Texas Showing',
    subtitle:
      'Texas rappers held more of the lineup than anyone outside the state expected — and the crowds reacted accordingly.',
    author: 'Diego Jauregui',
    date: '2026-04-10',
    displayDate: 'April 10, 2026',
    category: 'Festival Recap',
    venue: 'Hollywood Park',
    coverIndex: 3,
    readTime: '6 min read',
    body: [
      "Rolling Loud California wrapped at Hollywood Park last weekend, and the Texas presence on the lineup was bigger than anyone outside the state was framing it as. Across three days and four stages, you could have built an entire set out of just the Texas-born acts on the bill — and most of them outdrew their slot. Rolling Loud has been the dominant rap festival on the global circuit for nearly a decade, and the California weekend has historically been weighted toward LA artists and West Coast bookings. The 2026 edition felt different from the first day.",
      "## The Texas takeover",
      "The headliner conversation didn't include any Texans this year, which is fair — the biggest names on the top of the poster were East Coast and LA artists, plus the usual run of international bookings that Rolling Loud has been pushing into the mainline since 2022. But the mid-card was a different story. Crowds reacted to the regional sets the way you'd expect a hometown reaction — even though Hollywood Park is a long way from any of the cities these artists are from.",
      "That speaks to how much Texas rap has traveled in the last twelve months. The streaming numbers were already there, but festival crowd reactions are a more honest gauge of where an artist actually sits with the audience, and the regional reactions to Texas sets this year suggest the audience knows more than the booking suggested. By the end of day two, a handful of these acts should have been programmed two tiers higher on the bill.",
      "## Who made the most of it",
      "Two specific sets are going to define how this festival gets remembered. One was a Houston veteran's mid-afternoon slot that pulled a crowd nobody saw coming — the kind of overflow situation where the people who got there early ended up trapped against the barricade for the entire set. The performance lived up to the demand. Sixty minutes, no filler, no drops in energy, and a closing run of three career singles that resolved into one of the loudest crowd singalongs of the weekend.",
      "The other was a younger artist out of Dallas whose first major festival booking turned into the kind of viral moment that doesn't usually happen until day three. The set was scheduled for a smaller stage with a fraction of the audience the main stages were pulling. By the third song, the crowd had quadrupled. By the fifth, the festival staff had to open the side gates to clear pressure. By the end, the artist was getting tagged by festival accounts that had nothing to do with the booking — the kind of organic post-set bump that genuinely moves careers.",
      "## The Texas presence beyond the bill",
      "It wasn't just the lineup. The merch booths showed Texas affiliation across half the artists with their own setups. The DJ rotations between sets included Houston-screwed remixes that have become standard at every Rolling Loud weekend over the last few years. The food trucks were a third Texas barbecue. The festival doesn't program a vendor lineup, but the vendors clearly know where the energy is.",
      "## What it means going forward",
      "Rolling Loud's California weekend has historically been weighted toward LA acts and East Coast bookings. The reweighting toward Texas this year was visible from the schedule. Whether that's a one-time programming choice or a sign of where the festival is going next is the question that matters for the rest of 2026 — and given that Rolling Loud has been mid-conversation about adding a Texas weekend for years now, the answer might be coming sooner than expected.",
      "If a Rolling Loud Texas does end up happening, the conversation about American rap festivals shifts. The state's rap scene is now generating enough output to anchor a full bill. The California weekend was a useful test case. The next move is on the festival.",
    ],
    tags: [
      'Rolling Loud',
      'California',
      'Festival Recap',
      'Texas Rap',
      'Houston',
      'Dallas',
      '2026',
    ],
  },
]

export const articles: Article[] = [
  ...cityAndYeArticles,
  ...showRecapArticles,
  ...legacyArticles.filter((a) => !REPLACED_ARTICLE_SLUGS.has(a.slug)),
]

export const radarEntries: RadarEntry[] = []
