export type Article = {
  slug: string
  type: 'review' | 'spotlight' | 'preview'
  title: string
  subtitle: string
  author: string
  date: string
  displayDate: string
  category: string
  venue?: string
  coverIndex: number
  /** Optional path to a real cover/hero image. When set, replaces the gradient placeholder on cards and the article hero. */
  heroImage?: string
  readTime: string
  body: string[]
  tags: string[]
}

export type RadarEntry = {
  artist: string
  venue: string
  date: string
  genre: string
  note: string
}

export const articles: Article[] = [
  {
    slug: 'music-world-cup-2026-texas',
    type: 'preview',
    title: 'The 2026 World Cup Comes to Texas — And the Music Is Going to Be a Story of Its Own',
    subtitle:
      "Dallas hosts a semifinal at AT&T Stadium. Houston gets seven matches at NRG. For five weeks this summer, Texas is going to be one of the most-watched places on the planet — and the unofficial soundtrack is already being written.",
    author: 'Diego Jauregui',
    date: '2026-05-27',
    displayDate: 'May 27, 2026',
    category: 'Culture',
    coverIndex: 6,
    readTime: '6 min read',
    body: [
      "The 2026 FIFA World Cup kicks off on June 11th in Mexico City and runs through July 19th, when the final is played at MetLife Stadium outside New York. It's the largest World Cup in tournament history — 48 teams, three host countries across the USA, Mexico, and Canada, and eleven host cities in the United States alone. Two of those US host cities are in Texas: Dallas-Arlington at AT&T Stadium, which gets nine matches including a semifinal, and Houston at NRG Stadium, which hosts seven. For the better part of two months, the state is going to be one of the most-watched destinations on the planet. And music — rap culture especially — is going to be a huge part of how it actually plays out.",
      "## The official soundtrack",
      "FIFA's relationship with tournament music has been formal since the **Italia 90** cycle, and the 2026 official theme is expected to follow the recent template — a global pop collaboration with multiple artists, an English-language anthem, and regional companion tracks tied to each host country. The Mexico-USA-Canada split is going to make the music side more interesting than usual. Mexican music has been ascending globally for years now. Regional Mexican is the largest growth genre on streaming. Latin pop continues to dominate the international charts. The country's hip-hop and corridos tumbados movement is unavoidable. Expect the cultural component of the tournament to lean into all of it.",
      "## The unofficial soundtrack",
      "This is where it gets interesting. The official FIFA programming will be what it always is — corporate, polished, designed for global broadcast. The actual soundtrack of the tournament, the one that ends up tied to the cultural memory of the event, is going to come from somewhere else.",
      "Texas is hosting matches in two major rap cities. The Houston matches at NRG Stadium are happening in the most influential American rap city of the last thirty years. The Dallas matches at AT&T Stadium are happening in a metro that's quietly built one of the country's most active independent rap scenes. The amount of music-adjacent programming around these matches is going to be enormous — fan-zone activations, sponsor-backed concerts, brand collaborations, and the kind of grassroots promotion that always shows up around a major sporting event.",
      "## What's already happening on the ground",
      "Houston's promoters have been booking the surrounding weekends aggressively. The week of every NRG match is filling out with concerts, club nights, and fan-zone activations. **House of Blues Houston**, **713 Music Hall**, and **Toyota Center** are running calendars that overlap directly with match schedules. Watch parties are being organized by everyone from major bars to independent promoters operating out of warehouses in the East End.",
      "Dallas is doing the same — and more, because AT&T Stadium's nine-match schedule is the most match-heavy of any US venue. Deep Ellum bookings for June and July are already heavy, and the city's promoter community has been organizing for the tournament since the host-city announcement back in 2022. The amount of international music traffic that's going to land in DFW during the tournament window is going to be unlike anything the city has hosted before. Expect surprise sets, sponsor pop-ups, and tour stops you wouldn't normally see routed through Texas at all.",
      "## The cultural moment",
      "What makes the 2026 World Cup unusual, from a music perspective, is the alignment of three things at once: the largest tournament in history, host countries with some of the most developed live music infrastructure on the planet, and a moment when Latin music and Latin-adjacent rap are at their absolute peak of global influence. The cultural cross-pollination that's going to happen across these eight weeks is going to define how a generation of fans remembers the tournament.",
      "Expect collaborations to drop weekly. Expect artists to release tournament-tied singles. Expect the streaming charts in late June through late July to look unrecognizable compared to any normal summer. Expect Texas — both for the matches and for the cultural and music infrastructure around them — to be one of the biggest single beneficiaries of all of it.",
      "## What we're tracking",
      "StagePulse is going to be covering the music-adjacent side of the tournament throughout June and July — show announcements, fan-zone programming, watch-party venues, and the artists who end up most associated with the cultural moment of the matches in Texas. The tournament is sport. The cultural footprint around the tournament is everything else. We'll be filing from both sides.",
      "The whistle goes June 11. The soundtrack is already being written.",
    ],
    tags: [
      'World Cup 2026',
      'FIFA',
      'Houston',
      'Dallas',
      'Culture',
      'Texas Music',
      '2026',
    ],
  },
  {
    slug: 'austin-music-scene-2026',
    type: 'spotlight',
    title: "Austin in 2026: A Guide to the Venues, Artists, and Scene Worth Your Attention",
    subtitle:
      "The Live Music Capital of the World keeps earning the title — but the version of Austin that matters in 2026 isn't always the one in the brochure. A real-time map of where the music is.",
    author: 'Diego Jauregui',
    date: '2026-05-26',
    displayDate: 'May 26, 2026',
    category: 'City Guide',
    venue: 'Austin, TX',
    coverIndex: 2,
    readTime: '6 min read',
    body: [
      "Austin doesn't need an introduction to anyone who's paid attention to American music in the last forty years. The self-styled Live Music Capital of the World has been carrying that title officially since 1991, and the city's infrastructure — venues, festivals, recording studios, scene magazines — has been one of the most concentrated music ecosystems in the country for longer than most cities have had a scene at all. But 2026 is a transition year. The old Austin is changing fast, the rents are doing their thing, and what the city's actually producing right now looks different than the postcard version. This is what's worth your attention.",
      "## The flagship rooms",
      "**Stubb's Bar-B-Q** remains the city's most iconic outdoor amphitheater. The 2,000-capacity outdoor stage at the back of the restaurant has hosted basically every touring act that's come through Austin since the late nineties, and the indoor room handles the smaller bills. Even with the changes in the surrounding neighborhood, Stubb's outdoor stage on a clear night is still the single most quintessential Austin concert experience.",
      "**Emo's**, after multiple location moves over the last fifteen years, has settled into its current Riverside spot and now functions as the city's anchor for mid-sized touring hip-hop, alternative, and indie bookings. The room is large enough to feel like a real show and intimate enough to feel like a real room — same logic that's made Paper Tiger so important to San Antonio.",
      "**ACL Live at the Moody Theater** is the year-round home of the **Austin City Limits** television show and a separate touring venue in its own right. The room is built for broadcast, which means the production standards are higher than almost any other comparable venue in the state. If you want to see an artist look as good as they're ever going to look on a Texas stage, ACL Live is where it happens.",
      "## The smaller circuit",
      "**Mohawk**, on Red River, is the most important small room in Austin. The two-stage configuration — indoor and outdoor — lets the venue host two bills on the same night, and the booking is consistently strong across both stages. The outdoor stage in particular is one of the best urban concert spaces in the country.",
      "**Antone's**, the city's historic blues home base, has shifted under various ownership groups since the original Clifford Antone closure in 2006, but the current iteration on Fifth Street is doing what the original room did — anchoring the city's blues identity while opening up to roots, jazz, and Americana programming. The **Continental Club** on South Congress remains the gold standard for the old-Austin honky-tonk and roots tradition. **Hotel Vegas**, **Cheer Up Charlies**, **Empire Control Room**, and **The Parish** round out the smaller-room ecosystem and catch the bookings that don't fit the flagships.",
      "## What the city is actually producing",
      "Austin's national reputation is tied to indie rock, blues, and the singer-songwriter tradition. The current local output is broader. The rap scene has been quietly building for a decade — collectives like **Riders Against the Storm**, the long catalog of **Magna Carda**, and a newer generation that hasn't broken nationally yet but is moving real crowds in town. The Latin alternative and cumbia scenes are stronger now than at any point in the last twenty years. The DIY house show circuit is still active despite the rent pressure.",
      "**Spoon**, still operating out of Austin after three decades, remains the city's most respected indie rock export. **Black Pumas** continue to push neo-soul into territory that hasn't been touched since the early seventies. **Gary Clark Jr.** stays on the road and continues to do for Austin blues what Stevie Ray Vaughan once did. The under-card across all genres is deeper than the press coverage suggests.",
      "What's changed is the relationship between the scene and the city's branding. Austin's official image is still anchored in the festival economy — South by Southwest, ACL, the music tourism dollars — but the people actually making the music are increasingly operating outside of that economy, releasing on smaller labels, booking their own tours, and working day jobs to underwrite the operation.",
      "## The festival circuit",
      "**ACL** is the obvious one — the festival's deep dive is the subject of a separate preview on this site. **SXSW** has had a complicated few years; the 2026 edition continues the festival's pivot toward smaller, more curated showcases rather than the sprawling old-school model. **Hot Luck** and **Float Fest** are smaller seasonal anchors. The local showcase festivals — the ones the city's promoters and independent labels run themselves — are where the real discovery happens.",
      "## How to actually experience Austin music",
      "Skip the bachelorette-party Sixth Street stretch. Walk Red River, hit Mohawk and a smaller bill at the Parish. Make sure you've spent a night at the Continental Club. Eat at Hot Luck if it's the season. Go to a house show if you can find one. The Austin music scene that built the city's reputation is still there — you just have to look slightly past the marketing to find it.",
      "Live music capital is a claim. The city earns it nightly.",
    ],
    tags: [
      'Austin',
      'City Guide',
      'Live Music',
      'Texas Music',
      'Mohawk',
      "Stubb's",
      "Emo's",
      'ACL Live',
      '2026',
    ],
  },
  {
    slug: 'houston-rap-scene-rising-2026',
    type: 'spotlight',
    title: 'Houston Rap, Still Rising: How the Most Influential City in American Hip-Hop Keeps Building',
    subtitle:
      "Three decades after DJ Screw, the city is in the middle of its strongest run since the original screw era. A look at the legacy, the current wave, and what the under-card is about to do to 2026.",
    author: 'Diego Jauregui',
    date: '2026-05-25',
    displayDate: 'May 25, 2026',
    category: 'Scene Report',
    venue: 'Houston, TX',
    coverIndex: 7,
    readTime: '7 min read',
    body: [
      "Houston rap has been the most influential regional movement in American hip-hop for almost three decades. The chopped and screwed tradition that **DJ Screw** built in the early nineties redefined how rap could be produced. The **Geto Boys** and **Rap-A-Lot Records** put the city on the map nationally. **UGK** out of Port Arthur — close enough to share a metro — gave Southern rap its blueprint. **Scarface** released some of the most respected solo records the genre has produced. The list goes on. In 2026, the city is in the middle of its strongest run since the original screw era, and the names doing the work span four generations.",
      "## The legacy weight",
      "You can't write about Houston rap in 2026 without acknowledging what built the platform. DJ Screw passed in 2000, but the **Screwed Up Click** he built — Big Hawk, Big Moe, Lil' Keke, Z-Ro, Trae the Truth — defined Houston's identity as the slow-motion South. The screw tradition is no longer a regional sound; it's been absorbed by national rap, by experimental electronic music, by the streaming-era ambient catalog. Every chopped vocal you've heard on a major-label record in the last fifteen years owes back to the basement tapes Screw was making on Greenstone Street.",
      "**Bun B** continues to function as the city's elder statesman, the connector between the eras — also one of the most quoted ambassadors the genre has ever produced. **Scarface** remains the most respected MC the city has produced. **Slim Thug**, **Paul Wall**, **Mike Jones** — the mid-2000s wave — still tour, still release, still get reverence from the next generation. The veterans haven't aged out. They've integrated.",
      "## The current wave",
      "The current Houston wave is, to most outside listeners, dominated by three names: **Travis Scott**, **Don Toliver**, and **Megan Thee Stallion**. All three are global. All three are still Houston. Travis Scott's Cactus Jack label has functioned as a Houston export operation since 2018, and the city's influence on his production is in every record. Don Toliver's June stop at the Frost Bank Center (covered separately on this site) is the kind of Houston-to-San Antonio routing the city's previous generation rarely got. Megan Thee Stallion has done as much as any artist this decade to reposition Houston as a current city, not a legacy city.",
      "Below that tier, the depth is enormous. **Maxo Kream** has been releasing some of the most technically ambitious storytelling rap of the last decade, and his catalog deserves more national attention than it gets. **Tobe Nwigwe** has built a touring operation that fills theaters in cities the previous Houston generation never sold out. **Sauce Walka** continues to be one of the most active rappers in the country, releasing volume that most artists couldn't sustain. **BeatKing** has carved out a lane that combines club music with Houston tradition in a way nobody else is doing.",
      "## What's actually new",
      "What separates 2026 from 2024 or 2025 is the depth of the under-card. The current generation of Houston rappers in their early-to-mid twenties is the deepest the city has produced in years. Producers are working out of bedroom studios in the Heights, the Third Ward, southwest Houston, and the suburbs surrounding the city. Independent labels are operating with the kind of distribution savvy that wasn't available to the previous generation. The number of regionally relevant artists with releases this year alone is in the dozens.",
      "The streaming era has been good to Houston. The slow tempo of the city's signature sound translates well to the algorithm's playlist culture — the chopped, melodic, ambient pocket that Houston rap occupies happens to be exactly the kind of music that streaming environments reward. That's been quietly fueling the current generation in a way that the previous wave didn't get to benefit from.",
      "## The venues",
      "Houston's live rap infrastructure is the strongest in Texas. **Toyota Center** hosts the arena-level tours. **713 Music Hall** has filled the 2,500-3,000 cap mid-tier the city was missing. **White Oak Music Hall** handles the smaller-but-still-touring acts. **House of Blues Houston** runs the standard touring rotation. **NRG Stadium** hosts the stadium-scale stops when they happen, including the upcoming **World Cup matches** that will turn the city into one of the most-watched destinations on the planet for five weeks straight.",
      "The smaller club circuit — the **Continental Club**, **The Heights Theater**, various East End warehouse spaces — handles the local circuit and the early-career touring stops. Houston has more rap shows per capita than any city in Texas, and most of them never make it onto the national booking radar.",
      "## What's next",
      "The conversation about Houston rap in 2026 isn't whether it's relevant — that question got answered fifteen years ago. The question is how deep the bench is, how many of the under-card names are going to break out nationally, and whether the city's infrastructure can keep up with the volume of artists actively trying to operate professionally. Based on the spring's release calendar alone, the answer to the first two questions is going to be obvious by the end of summer.",
      "The city has been the most important rap city in America at multiple points in the last thirty years. It's about to be again.",
    ],
    tags: [
      'Houston',
      'Houston Rap',
      'Scene Report',
      'DJ Screw',
      'Don Toliver',
      'Travis Scott',
      'Megan Thee Stallion',
      'Maxo Kream',
      'Tobe Nwigwe',
      'Texas Music',
      '2026',
    ],
  },
  {
    slug: 'san-antonio-live-music-guide-2026',
    type: 'spotlight',
    title: "The San Antonio Live Music Guide: Where to Actually Go in 2026",
    subtitle:
      "Seventy-five miles south of Austin and forever compared to it — the SA scene runs deeper than the marketing suggests. A working guide to the rooms, the strip, and the music actually getting made here.",
    author: 'Diego Jauregui',
    date: '2026-05-24',
    displayDate: 'May 24, 2026',
    category: 'City Guide',
    venue: 'San Antonio, TX',
    coverIndex: 4,
    readTime: '6 min read',
    body: [
      "San Antonio's live music scene is one of the most underrated in the country. The city sits seventy-five miles from Austin and gets compared unfavorably to its neighbor constantly, which is fair if you're only looking at festival economy — Austin's scale is in a different category. But on a venue-by-venue, week-by-week basis, San Antonio's actual live music infrastructure is denser, more diverse, and more economically accessible than most people realize. We've been working out of SA since the site launched. Here's what we've learned about the rooms, the scenes, and where to actually go.",
      "## The flagship rooms",
      "**Paper Tiger**, on the Saint Mary's strip, has become the most important venue in the city. 1,200-capacity, former auto shop, no balcony, no VIP section — just a room. We have a separate spotlight on the venue on this site if you want the full breakdown, but the short version is that Paper Tiger's booking team is consistently three steps ahead of every other room in town, and the calendar reflects that.",
      "**The Aztec Theatre**, downtown, is the city's beautifully restored 1920s vaudeville house. About 1,800-cap, gorgeous interior, and a programming slate that has shifted significantly over the last three years toward touring hip-hop, alternative, and indie bills. The Freddie Dredd / Back to Hell stop covered separately on this site is exactly the kind of show the room has been catching this cycle.",
      "**The Majestic Theatre**, also downtown, is the larger sister venue — 2,300 capacity in the same kind of restored vaudeville-era setting. The booking leans theater-scale: Broadway tours, comedy, larger touring music acts that prefer a seated venue. **The Tobin Center for the Performing Arts**, just north of downtown, covers similar ground from a more contemporary architectural setting and has become the city's home for classical, jazz, and large-scale Latin programming.",
      "**The Frost Bank Center**, on the east side, is the arena. 18,500 for concerts, primarily used for Spurs games and the larger arena tours. Don Toliver's June stop (covered separately) is the kind of routing the room is built for.",
      "## The smaller circuit",
      "Below the flagship rooms, the smaller circuit is where the actual scene lives. **Sam's Burger Joint** has been running a consistently strong booking calendar for over twenty years and is one of the only rooms in town doing reliable under-21 programming. **The Lonesome Rose**, near Paper Tiger on the Saint Mary's strip, anchors the country and Americana side of the scene and runs one of the best outdoor patios in the city. **Limelight** handles a lot of the city's punk, hardcore, and harder-edge metal bookings — small, loud, exactly what it needs to be.",
      "**Hi-Tones**, across the street from Paper Tiger, is the post-show bar that doubles as a music room itself when the booking demands it. The whole Saint Mary's strip operates as a single neighborhood-scale entity, with the venues, bars, and food spots functioning as a connected ecosystem.",
      "## The Saint Mary's strip",
      "The Saint Mary's strip is the heart of the SA music scene. The run of bars, music venues, and food spots along North Saint Mary's Street, just north of downtown, has been the home of the city's independent music culture for two decades. It's one of the few neighborhoods in Texas where you can walk between three or four legitimate music rooms in a single night. The strip operates more like Austin's old Red River district than like the rest of San Antonio.",
      "## What's actually being produced",
      "San Antonio's musical output has historically been overshadowed by the much larger Austin scene to the north and the much louder Houston rap scene to the east. That's been changing. The city's hip-hop scene is exporting artists nationally for the first time in a decade. The Latin alternative and cumbia scenes are stronger than at any point in recent memory. The Tejano and conjunto tradition continues to anchor the city's cultural identity, and a younger generation of musicians is engaging with that tradition in interesting new ways — bringing it into conversation with R&B, electronic music, and indie production.",
      "What's missing, frankly, is the press infrastructure. Austin has the Austin Chronicle. Houston has the Houston Press and a half-dozen other outlets. San Antonio has a smaller editorial ecosystem, and a lot of what's actually happening in the scene doesn't get documented at the time it happens. That's part of why this site exists.",
      "## How to use this guide",
      "If you're in San Antonio for the first time and you want to understand the music scene: walk the Saint Mary's strip on a weekend night. Stop at Paper Tiger if there's a show. Eat at one of the strip's food spots. Catch a set at Hi-Tones if Paper Tiger's not running. End the night on the Lonesome Rose patio.",
      "If you live here and you've been sleeping on the scene: pick a venue, pick a night, show up. The work has been getting done. The audience just needs to catch up.",
      "More venue spotlights and scene coverage coming through the summer. Show tips welcome via the contact page.",
    ],
    tags: [
      'San Antonio',
      'City Guide',
      'Paper Tiger',
      'Aztec Theatre',
      'Saint Marys Strip',
      'Live Music',
      'Texas Music',
      '2026',
    ],
  },
  {
    slug: 'dallas-concert-culture-2026',
    type: 'spotlight',
    title: 'Dallas Concert Culture in 2026: Deep Ellum, the Stadiums, and Everything in Between',
    subtitle:
      "The largest live music economy in Texas, the most underrated independent scene in the state, and a tournament summer that's about to put the city on every international map at once.",
    author: 'Diego Jauregui',
    date: '2026-05-23',
    displayDate: 'May 23, 2026',
    category: 'City Guide',
    venue: 'Dallas-Fort Worth',
    coverIndex: 1,
    readTime: '6 min read',
    body: [
      "Dallas-Fort Worth has the largest live music economy in Texas by raw revenue and total capacity, and one of the most underrated independent scenes in the country. The metro's reputation gets pulled in two directions: the corporate, festival-and-stadium side that drives the big numbers, and the scrappier Deep Ellum club circuit that's been doing serious work for fifty years and rarely gets the press to match. In 2026, both sides are running strong. Here's what's happening, what the rooms are doing, and why DFW's concert culture is worth paying more attention to.",
      "## Deep Ellum, still the anchor",
      "Deep Ellum has been Dallas's music neighborhood since the 1920s. The blues, jazz, and ragtime history of the district laid the groundwork; the punk and post-punk waves of the seventies and eighties cemented it; the current era of independent rooms keeps it active. **Trees**, **Granada Theater**, **The Factory in Deep Ellum**, and **Deep Ellum Art Co.** anchor the current generation of venues, supported by a network of smaller bars and DIY spaces that fluctuate but never fully disappear.",
      "**Granada Theater** is the consistent flagship. The 1,100-capacity former movie palace has been a music venue since the seventies, and the current ownership has built it into one of the most respected mid-sized rooms in the country. The booking is genuinely eclectic — indie rock, hip-hop, jazz fusion, country, experimental — and the room itself is one of the visually most striking music halls in Texas.",
      "**Trees**, in Deep Ellum proper, is the city's harder-to-categorize room. Punk, hardcore, niche hip-hop, experimental electronic — Trees catches the bookings that are too weird or too small for Granada and too big for the bar circuit. If you want to see what Dallas's actual scene looks like, the Trees calendar is where you start.",
      "**The Factory in Deep Ellum** — the former Bomb Factory, rebranded after a 2020 ownership change — handles the bigger touring stops. Around 4,300-capacity, indoor warehouse-style architecture, and a booking team that consistently pulls the harder-rotation hip-hop and rock tours the city's other rooms don't have the capacity for.",
      "## The bigger rooms",
      "**American Airlines Center** hosts the arena-scale tours, both music and otherwise. **Toyota Music Factory** in Irving handles the larger amphitheater bookings — the indoor theater and the outdoor pavilion cover the range of mid-to-large touring acts. **AT&T Stadium** in Arlington hosts the stadium-scale tours and is also one of the eleven US host venues for the **2026 FIFA World Cup**, including a semifinal. The city is hosting an enormous music-adjacent moment this summer that goes well beyond concerts (we have a separate piece on what that means for Texas).",
      "**House of Blues Dallas** and **South Side Music Hall** fill in the rest of the mid-tier. Each has its own booking identity. Neither is doing what Granada or the Factory are doing, but both stay busy.",
      "## The rap scene",
      "Dallas rap in 2026 is a producer's town. The lineage runs through Memphis-influenced low-end, Houston-screwed cadence, and Latin and reggaeton-adjacent textures that are becoming a Dallas signature. The rappers come second to the people building the beats — and the beats are some of the most adventurous regional production happening anywhere right now.",
      "The artist roster is deep. **Erykah Badu** remains Dallas's most influential cultural export, and her continued investment in the city's scene — the Badu World Market, her mentorship of younger artists, her continued residency at smaller rooms — keeps her in the conversation in a way that legacy artists usually aren't. The under-card includes **Erica Banks**, **Yella Beezy**, the late **Mo3**'s ongoing catalog influence, **That Mexican OT** (Bay City, but very much in the DFW conversation), and a younger generation of artists releasing on independent labels that the major-label A&R community is actively scouting.",
      "## What's next",
      "The big story in Dallas this year is the World Cup. AT&T Stadium's match calendar — nine games including a semifinal — is going to bring more international attention to the city than any single event has in years. That attention is going to spill over into the music economy. Promoters are already booking the surrounding weeks aggressively, and the Deep Ellum bar and venue calendar is filling out with international stops that wouldn't otherwise have been on the books.",
      "For the rest of 2026, watch the producer scene. Watch the Granada and Trees calendars. Watch the Deep Ellum block as a whole — the gentrification pressure is real, but the music infrastructure is still standing, and the city's independent scene has been written off enough times to know how to survive the next decade.",
      "Dallas has always been a music town. The press just hasn't always noticed.",
    ],
    tags: [
      'Dallas',
      'Deep Ellum',
      'City Guide',
      'Granada Theater',
      'Trees',
      'AT&T Stadium',
      'World Cup 2026',
      'Texas Music',
      '2026',
    ],
  },
  {
    slug: 'acl-2026-preview-texas-acts',
    type: 'preview',
    title: 'ACL 2026 Preview: The Texas Acts Worth Showing Up Early For',
    subtitle:
      'Six homegrown artists buried in the undercard who could steal the festival before the headliners hit the stage.',
    author: 'Diego Jauregui',
    date: '2026-05-22',
    displayDate: 'May 22, 2026',
    category: 'Festival Preview',
    venue: 'Zilker Park, Austin',
    coverIndex: 3,
    readTime: '5 min read',
    body: [
      "The 2026 Austin City Limits lineup dropped earlier this month, and as is tradition, the conversation went immediately to the headliners. That's how festivals work — the names at the top of the poster do the press cycle, sell the tickets, and frame the story. But the bigger story this year is happening lower on the bill, where Texas artists are stacked across the four days in a way ACL hasn't programmed in years.",
      "The names are smaller, the set times are mid-afternoon, and the press cycle hasn't bothered to flag them yet. But anyone watching the Texas scene over the last twelve months should already have a few of these acts circled. ACL has always been about more than its headliners — the festival has been a launching pad for regional artists since **C3 Presents** started running it at Zilker Park in 2002, and the 2026 booking might be the strongest case for that model in a decade.",
      "## Who's worth getting there early for",
      "The Texas presence cuts across genre and city. A Houston rapper coming off her best year ever and a major-label rollout that's expected to peak right around festival weekend. An Austin indie band whose debut album landed harder than anyone expected and is reportedly already cutting their sophomore record. A San Antonio-rooted R&B project that's been quietly opening for everyone — including two arena tours we tracked through Texas this spring. A Dallas production duo whose late-2025 mixtape is going to age into a regional classic, and whose first ACL booking lands them on one of the festival's main stages during golden hour on Saturday.",
      "None of them are headlining. All of them are worth showing up for. The right move with ACL has always been to build your weekend around the smaller-stage discoveries and let the headliners be whatever they're going to be. This year, that math is more obvious than usual.",
      "## Why this lineup feels different",
      "ACL has historically been weighted toward national bookings. Local programming has been there but light, often pushed to the smaller stages on Sunday afternoon when half the crowd is already cooked from two days of sun. The result was a festival that lived in Austin but didn't really sound like it.",
      "This year reads different. Whether that's intentional curation or a reflection of how much Texas music has shifted is impossible to say from outside. The state's hip-hop output has exploded since 2023. Houston is producing more relevant names than at any point since the screw era. Dallas has the most active independent scene it's had since the late 2000s. San Antonio is exporting artists for the first time in a decade. ACL would have to be deliberately ignoring all of that to not reflect it — and the 2026 schedule suggests they're done ignoring it.",
      "## How to actually plan your weekend",
      "The trap with ACL is the headliner FOMO. People plan their day around 9 PM closers and miss everything that mattered. The Texas slots this year are concentrated in the 2 PM - 6 PM window across all four festival days. Get to Zilker by lunch, do the rounds, and you'll see the festival most people are going to miss.",
      "Both weekends are running the same lineup. Weekend One sells out faster and has more energy on day one. Weekend Two has better crowd density, shorter food lines, and slightly cooler weather. If you're flexible, Weekend Two is the better experience for the same lineup. If you can't be flexible — get tickets, get there early, build the day around the under-card.",
      "[NOTE] Full lineup and set times at aclfestival.com. We'll have on-the-ground coverage from both weekends — show tips and recommendations welcome via the contact page.",
    ],
    tags: [
      'ACL Festival',
      'Austin',
      'Festival Preview',
      'Texas Music',
      'Live Music',
      '2026',
    ],
  },
  {
    slug: 'acl-festival-2026-full-preview',
    type: 'preview',
    title: 'ACL 2026: The Complete Preview',
    subtitle:
      "Two weekends. Eight stages. A quarter-million people. The biggest music event in Texas every year is back — here's the lineup, the layout, and how to actually do it.",
    author: 'Diego Jauregui',
    date: '2026-05-21',
    displayDate: 'May 21, 2026',
    category: 'Festival Preview',
    venue: 'Zilker Park, Austin',
    coverIndex: 2,
    readTime: '7 min read',
    body: [
      "Austin City Limits is the biggest music event in Texas every year, and one of the most important festivals in the country period. The festival takes over Zilker Park for two weekends in early October — six days of music across eight stages, a quarter-million attendees total across both weekends, and a lineup that's run from Paul Simon to Tyler, The Creator to Kendrick Lamar without losing its identity along the way. The 2026 edition is the festival's twenty-fourth year, and based on the lineup **C3 Presents** announced earlier this month, it might be one of the strongest of the recent run.",
      "## What ACL actually is",
      "ACL was launched in 2002 by C3 Presents, an Austin-based promotion company that has since become one of the largest concert promoters in the world. The festival shares a name with the long-running **Austin City Limits** television show — the PBS music program that's been broadcasting from Austin since 1974 — but the festival and the show are now separately operated, with the festival functioning as the larger-scale commercial sibling to the show's smaller, more focused taping format.",
      "The festival runs across both weekends of early October every year — this year, October 2-4 and October 9-11. The same lineup plays both weekends, with a handful of artist-specific exceptions. Weekend One sells out faster and gets the bigger press cycle. Weekend Two has better crowd density, shorter food lines, and slightly cooler weather. If you have the flexibility, Weekend Two is the better experience.",
      "## The 2026 lineup",
      "The 2026 headliners have not been universally well-received — the social media reception was the usual mix of complaints about repeat bookings and complaints about not enough rap, country, or whatever the complainer's preferred genre is. That's how festival announcements work. The bill is deeper than the headliner conversation suggests, and the mid-card programming this year is unusually strong. (We have a separate piece on the Texas acts buried in the under-card — worth reading if you're planning your schedule.)",
      "Genre-wise, the festival continues its slow shift toward broader programming. The 2022-2024 lineups leaned heavier on hip-hop than the festival's first decade did, and the 2026 edition continues that trend without abandoning the indie rock and singer-songwriter identity the festival was originally known for. The Latin programming has gotten genuinely strong over the last three years, and the country and Americana stages are doing some of the festival's most interesting booking — even relative to Austin's broader music identity.",
      "## What to expect on the ground",
      "Eight stages, all running in parallel, all weekend long. The flagship stages — the American Express stage at the south end of the field, the Honda stage at the north end — host the biggest acts. The mid-tier stages host the mid-card. The smaller stages, especially the Tito's Stage and the BMI Stage, are where the festival's discovery moments happen.",
      "Set times are aggressive. There's almost always a conflict between two acts you want to see, and the festival's geography means moving between stages takes ten to fifteen minutes if the crowds are heavy. Plan the day, accept that you'll miss things, and stay flexible.",
      "## Tips for attending",
      "The basics: hydrate, eat enough food, wear sunscreen, and accept that Austin weather in early October is unpredictable. Some years are 95 degrees. Some years are 65 and pouring. Dress in layers.",
      "Get to Zilker before noon. The line at the gates after 1 PM is significantly worse than the early-morning line, and the mid-afternoon discovery acts are some of the festival's best programming. The early hours are also when the food trucks are at their best — by 8 PM the lines are 45 minutes, and the most popular vendors are often sold out.",
      "Cash bars are gone — the festival is fully cashless. Bring sealed water, but accept that you'll be refilling at the free water stations all day. Sunscreen and a hat will save your weekend. A small backpack that meets the festival's size restrictions (check the website for current rules) is worth the effort.",
      "The transportation situation is the trickiest part. Parking around Zilker is impossible. The festival offers shuttle service from satellite lots, the city has occasionally run a temporary rail line for the event, and ride-share gets brutal at peak hours. The smartest move is to stay downtown, take the festival shuttle in, and walk back across the bridge after closeout.",
      "## Why ACL still matters",
      "In a year when festivals across the country are folding, downsizing, or pivoting to electronic-music-only formats, ACL's continued scale and curatorial range stands out. The festival has stayed financially viable, programmed both legacy and emerging acts, and never compromised on its Austin identity even as the city's gotten bigger and the festival's gotten more national. C3's operational discipline is part of that. The city's investment in Zilker Park and the surrounding infrastructure is part of it. The festival's audience — generally a slightly older, more committed concert-going crowd than the EDM-heavy peer festivals — is the rest.",
      "ACL is the biggest music event in Texas. It's also one of the biggest in the country. Six days, two weekends, 250,000 people. The city of Austin doesn't really pause for it — it just absorbs it. That's the trick.",
      "[NOTE] Full lineup and set times at aclfestival.com. Weekend One: October 2-4. Weekend Two: October 9-11. We'll have full on-the-ground coverage from both weekends — daily wrap-ups, photo coverage, and post-festival recaps.",
    ],
    tags: [
      'ACL Festival',
      'Austin',
      'Festival Preview',
      'C3 Presents',
      'Zilker Park',
      'Live Music',
      '2026',
    ],
  },
  {
    slug: 'don-toliver-frost-bank-center-san-antonio-2026',
    type: 'preview',
    title: 'Don Toliver Brings the Hardstone Psycho Tour to the Frost Bank Center',
    subtitle:
      'The Houston-born rapper is back on Texas soil for one night only — and the production is built for the room.',
    author: 'Diego Jauregui',
    date: '2026-05-20',
    displayDate: 'May 20, 2026',
    category: 'Show Preview',
    venue: 'Frost Bank Center',
    coverIndex: 1,
    readTime: '5 min read',
    body: [
      "Don Toliver is back in Texas, and the stop he's making at the Frost Bank Center on June 7 is the kind of show San Antonio rarely gets without making it onto the back half of a national tour. It's not the biggest room in the state — the Frost Bank Center holds around 18,500 for concert configurations — but for one night, it's going to be the loudest. Tickets dropped earlier this spring and the room is almost out.",
      "Toliver is Houston-born, raised in the Hiram Clarke area, and built his career through the **Cactus Jack** pipeline. He broke through nationally with **Heaven or Hell** in 2020, doubled down with **Life of a DON** in 2021, refined the sound on **Love Sick** in 2023, and pushed the catalog into its most ambitious territory yet with **Hardstone Psycho** in 2024. That last record is the one this tour is built around — and it's the record that finally gets him out of the supporting-act category and into a lane that's entirely his own.",
      "## What to expect on the night",
      "The Hardstone Psycho tour leans into the album's psychedelic, near-arena R&B production. Live, that translates to a wall of low end, real visual design — not the standard rap show LED package — and a setlist that moves between Toliver's biggest hits (**No Idea**, **After Party**, **Lemonade**) and the more atmospheric, slow-burning cuts the new record is built around. The opener slot is being filled by a rotating cast of Houston-affiliated acts across the tour; for the San Antonio date, the support hasn't been officially announced as of writing.",
      "Toliver's vocal approach — that half-sung, melodic-but-detached delivery that's basically his signature now — translates remarkably well to a room the size of the Frost. His producers have been touring with him for the last two years, so the mix should hold up. This is not a show where the studio polish gets lost in the live translation.",
      "## Why this stop matters",
      "Houston acts coming to San Antonio is not unusual. Houston acts at this scale stopping in San Antonio while the same tour is also booking Toyota Center is. The booking team chose this room on purpose. Toliver's last solo headlining tour skipped over Texas's second-largest market entirely, routing straight from Houston to Phoenix. The decision to add the Frost Bank Center this cycle reads as a deliberate market expansion — and it's a compliment to San Antonio that should not go unnoticed.",
      "The Cactus Jack ecosystem has always had a complicated relationship with the Texas cities outside Houston. For one of the brand's most successful breakout signees to choose this stop says something about where the market is — and about where the SA audience has finally been recognized to be.",
      "## Logistics",
      "Doors at 7 PM. Show starts at 8. The Frost Bank Center is on the east side, parking is plentiful but expensive ($25+ for premium lots), and ride-share is the easier move from downtown. Tickets are still available as of writing — but only barely, and not at the price they started at. The Verified Resale market is already showing prices 2-3x face.",
      "If you've been on the fence, stop being on it. This is the rare Texas headlining stop on a tour built for arenas, in a room half the size. That math doesn't last.",
      "[TICKETS]",
    ],
    tags: [
      'Don Toliver',
      'Houston',
      'San Antonio',
      'Frost Bank Center',
      'Hardstone Psycho',
      'Cactus Jack',
      'Show Preview',
    ],
  },
  {
    slug: 'texas-artists-to-watch-all-genres-2026',
    type: 'spotlight',
    title: 'The Texas Artists to Watch in 2026 — Across Every Genre',
    subtitle:
      "Country, rap, R&B, indie, Latin alternative, electronic. The depth of the state's output across every scene at once is the real story of Texas music this year.",
    author: 'Diego Jauregui',
    date: '2026-05-19',
    displayDate: 'May 19, 2026',
    category: 'Artist Roundup',
    coverIndex: 4,
    readTime: '6 min read',
    body: [
      "The Texas music scene in 2026 has more depth across more genres than at any point in the last decade. The rap conversation has been covered separately on this site (the six-artist roundup is worth your time), but the bigger story — the one that doesn't get the press attention — is how broad the state's output has become. Indie, R&B, country and Americana, Latin alternative, electronic, jazz — there are working artists from Texas right now doing some of the most adventurous work in their respective lanes, and the names below should be on your radar through the rest of the year.",
      "This isn't a comprehensive list. It's a snapshot of the artists whose 2026 trajectories we're tracking most closely — the ones whose moves are likely to define how Texas music is remembered when this year is over.",
      "## The country and Americana lane",
      "Texas country has been having a generational moment for three years running now. **Charley Crockett** continues to be one of the most prolific working musicians in the genre — his release pace borders on absurd, and the catalog is consistently strong. The newer wave of Texas country — artists working out of the Hill Country corridor between Austin and San Antonio, releasing on independent labels and touring relentlessly — is producing some of the most respected roots music in America right now. The contrast with the Nashville mainstream couldn't be more visible. Where Nashville continues to over-polish and over-produce, the Texas independent country scene is doing the opposite — sparser, more honest, more interested in songwriting than in radio format.",
      "## The R&B and soul wave",
      "**Black Pumas** remain one of the most influential current soul acts from Texas, working out of Austin and pushing the genre into territory that hasn't been touched since the early seventies. **Leon Bridges**, from Fort Worth, continues to release records that get critical attention and Grammy nominations in roughly equal measure. **Bobby Sessions** out of Dallas operates more in the rap-and-R&B borderlands but the soul side of his output deserves more attention than it gets. The under-card includes a generation of younger R&B artists working out of Houston and Dallas whose names will be familiar to people inside the scene and obscure to everyone else — that gap is about to close.",
      "## The indie and rock contingent",
      "**Spoon**, still operating out of Austin, remains one of the most respected indie rock bands in the country after three decades of active touring. **White Denim**, also Austin, continues to release records that quietly outperform their press cycle. **Khruangbin**, technically Houston, has built an international following on the strength of a deeply specific instrumental aesthetic nobody else is doing. The state's indie output has shifted somewhat away from the rock identity that defined the 2000s and 2010s in favor of more electronic, more genre-fluid releases, but the foundational scene is still there.",
      "## The Latin alternative wave",
      "This is where the most growth has been. Texas's Latin alternative scene — broadly, the artists working in the space between regional Mexican, cumbia, indie rock, and pop — has been ascendant since 2022. Artists working out of San Antonio, Houston, and Austin are releasing some of the most adventurous bilingual music in America right now, and the festival circuit has finally caught up to the audience that's been there all along. Expect the second half of 2026 to produce a breakout act from this scene that ends up on national playlists by the end of the year.",
      "## The electronic and experimental edge",
      "Austin and Houston both have working electronic scenes that operate mostly outside the festival circuit. The kind of work being done in warehouse spaces and small clubs in both cities — ambient, drone, IDM, experimental dance — has been growing in scale for years, and the international touring presence of artists associated with both cities is the highest it's been in a decade. The crossover into hip-hop production has been the most visible result of the scene's growth.",
      "## The producer class",
      "The most underrated part of the Texas music conversation is the production work. The state has produced some of the most respected hip-hop and pop producers of the last thirty years — **Mike Dean** out of Houston, the production lineages of the screw era, the current generation of beat-makers working out of Dallas — and the producer-as-artist model continues to thrive across the state. Expect at least one Texas-affiliated producer to land a Billboard top-ten production credit by Q3.",
      "## What's actually new",
      "What separates 2026 from any previous year isn't the existence of any one of these scenes — it's the simultaneous strength of all of them. Texas has historically had strong moments in country, in rap, in R&B, in indie rock individually. In 2026, all five are running at full strength simultaneously. That hasn't been true in this state since the early seventies, when the cosmic-country, outlaw-country, and Houston rap origins were all converging in real time.",
      "Watch the names above. Watch the names we haven't gotten to yet. Texas music in 2026 has more entry points than at any point in living memory. Pick one and start there.",
    ],
    tags: [
      'Texas Music',
      'Artist Roundup',
      'Country',
      'R&B',
      'Indie',
      'Latin Alternative',
      'Electronic',
      'Spoon',
      'Black Pumas',
      'Charley Crockett',
      'Leon Bridges',
      '2026',
    ],
  },
  {
    slug: 'texas-summer-concert-guide-2026',
    type: 'preview',
    title: 'Your Texas Summer Concert Guide: The Shows Worth Marking Down',
    subtitle:
      "From outdoor amphitheaters in Austin to club dates on the Saint Mary's strip, here's where the energy is going to be.",
    author: 'Diego Jauregui',
    date: '2026-05-18',
    displayDate: 'May 18, 2026',
    category: 'Show Guide',
    coverIndex: 2,
    readTime: '6 min read',
    body: [
      "Summer in Texas is brutal, but the concert calendar makes up for it. Between the outdoor amphitheaters running their gates open until midnight, the indoor venues running their AC on max, and the festival circuit moving through Austin and Houston, the next four months are going to be unrelenting. We've been working through promoter announcements all spring — here's what we're marking down, city by city, and where we think the energy is going to be.",
      "## San Antonio",
      "**Paper Tiger** continues to do most of the heavy lifting for SA's underground bookings — three or four shows worth flying in for already on the books through August. The 1,200-cap room on the Saint Mary's strip has built a reputation for catching artists right before they outgrow rooms this size, and the summer lineup follows the pattern.",
      "**The Aztec Theatre**'s run of touring rap dates is also unusually deep this year. After the Freddie Dredd / Back to Hell stop in May, the Aztec is hosting a series of mid-level hip-hop and alternative bookings that would have routed past San Antonio entirely two years ago. **The Tobin Center** and **Majestic Theatre** are running their usual mix of theater-scale tours, jazz and Latin programming, and one-night-only specials — the Majestic's summer slate in particular is worth a full look. The **Frost Bank Center** has the **Don Toliver** stop on June 7 (covered separately on this site) and a handful of other arena dates worth marking.",
      "Don't sleep on **Sam's Burger Joint** and **The Lonesome Rose** for smaller bills. The Lonesome Rose's outdoor patio is the best low-key summer move in the city, and Sam's is one of the only rooms in town doing consistent under-21 booking.",
      "## Austin",
      "**Stubb's**, **Mohawk**, **Empire**, **ACL Live at the Moody Theater** — the rotation is on its normal cycle, with Stubb's outdoor amphitheater taking the bulk of the touring stops. **Antone's** continues its decades-long run as the city's blues home base, and **Emo's** has the most reliable mid-tier hip-hop and alternative calendar of any room in the city.",
      "The bigger story is the festival circuit. **ACL** in October is the obvious headliner (we have a full preview on this site). But the run of smaller festivals in June and July — **Hot Luck** on the food-and-music side, **Float Fest**, and the various one-day showcase events — are doing some of the more interesting booking this year. Watch the smaller bills.",
      "## Houston",
      "**White Oak Music Hall** is having its strongest summer in years. The newer **713 Music Hall** has filled a gap in the 2,500-3,000 cap range the city was missing. **Toyota Center** is hosting two of the bigger Texas-tied tours and a handful of national stops worth crossing the state for, and **NRG Stadium** has a stadium-level show or two on the books in addition to the **World Cup** matches in June and July.",
      "Houston's smaller rooms — **The Heights Theater**, **Continental Club** Houston, the various warehouse-district pop-ups — are also worth tracking. Houston has more rap shows per capita than any city in Texas, and most of them never make it onto the national booking radar.",
      "## Dallas-Fort Worth",
      "**Granada Theater** is the consistent flagship for Deep Ellum bookings. **The Factory in Deep Ellum** is doing the bigger touring stops. **House of Blues Dallas** and **South Side Music Hall** round out the mid-tier. **American Airlines Center** has a handful of arena dates that will move tickets fast. **AT&T Stadium** is going to be dominated by the World Cup through July, but the surrounding bookings — at smaller rooms and across Deep Ellum — are going to benefit from the international foot traffic.",
      "**Trees** in Deep Ellum continues to be the room where the city's harder-to-categorize bookings end up — punk, hardcore, experimental electronic, niche hip-hop. If you want to see what Dallas's actual scene looks like, the Trees calendar is where you start.",
      "## What we're tracking",
      "We'll keep this updated through Labor Day. New show announcements get added as confirmations come in, and we'll flag the ones we're going to be at with photo and review coverage. Show tips welcome at the contact page — promoters, publicists, and fans all get the same response window.",
      "Summer's already started. The shows aren't waiting on you.",
    ],
    tags: [
      'Texas Music',
      'Summer 2026',
      'Show Guide',
      'San Antonio',
      'Austin',
      'Houston',
      'Dallas',
    ],
  },
  {
    slug: 'texas-rappers-to-watch-2026',
    type: 'spotlight',
    title: 'Six Texas Rappers Defining 2026',
    subtitle:
      'A roundup of the homegrown artists shaping how the state sounds this year — from Houston veterans to San Antonio newcomers.',
    author: 'Diego Jauregui',
    date: '2026-05-12',
    displayDate: 'May 12, 2026',
    category: 'Artist Roundup',
    coverIndex: 0,
    readTime: '7 min read',
    body: [
      "The Texas rap scene in 2026 doesn't have a center. That's the point. What used to be a Houston-dominated conversation has split open — Dallas is building its own gravity, San Antonio is moving artists nationally for the first time in a decade, and Austin is producing rappers who don't sound like anyone else's idea of an Austin rapper. The state's hip-hop output has more momentum right now than at any point since the early screw era, and the names doing the work span four cities, three generations, and basically every micro-genre rap has invented.",
      "This list isn't a comprehensive ranking. It's six acts shaping how the state actually sounds in 2026 — the artists whose moves we've been tracking show-to-show, release-to-release, and whose work has changed something about the conversation around Texas rap this year.",
      "## The Houston veterans still raising the ceiling",
      "The list opens where every Texas rap conversation has to open: Houston. The veterans who built the platform are still here, still releasing, and still cranking out music that beats almost anything the rest of the country is putting up. **Maxo Kream**'s last album was one of the most underrated Houston records of the decade. **Tobe Nwigwe** has built a touring operation that fills theaters in cities Houston rappers historically did not fill theaters in. **Don Toliver** remains one of the most distinctive vocal artists in modern rap, and his **Frost Bank Center** stop in June (covered separately on this site) is the headliner conversation for SA this summer.",
      "The model these artists laid down — slow, low, unhurried, regional in every way that matters — has never been more influential. New artists from outside Texas are copying the cadences. New producers are studying the catalog. The veterans aren't just present; they're still shaping what the new generation sounds like.",
      "## The San Antonio movement",
      "This is the part nobody outside Texas is talking about yet. Three artists in their early twenties, all from the south side, all releasing on their own labels, all booking out-of-state. The sound is different from the Houston tradition — colder, more electronic, less interested in trap drums than in what's happening overseas with UK drill and European cloud rap — but the work ethic is straight off the freeway.",
      "What's most interesting is the visual presentation. SA's new wave is releasing tightly art-directed videos and rollouts that look closer to a New York indie release than the loose, posse-shot Houston tradition. The aesthetic discipline matches the music's restraint. If you've been wondering what San Antonio rap was waiting for, the wait is over.",
      "## Dallas and the production-driven wave",
      "Dallas in 2026 is producer's town. The rappers come second to the people building the beats, and the beats are some of the most adventurous regional production happening anywhere right now. The lineage runs through DJ Premier-influenced sample work, Memphis-adjacent low-end, and a real comfort with Latin and reggaeton textures that's becoming a Dallas signature.",
      "The whole scene is one major-label A&R signing away from breaking out, and most of the people in it know it. Half the producers we follow have been in and out of LA over the last six months for sessions with artists whose names we can't print yet. By Q3 of this year, expect at least one Dallas-affiliated production credit on a Billboard top-ten record.",
      "## The Austin outliers",
      "Austin's rap scene has historically been small, fragmented, and overshadowed by the city's indie rock and live music identity. That's changing. The rappers coming out of Austin in 2026 — collectives like **Riders Against the Storm** have been working at this for years, and a younger generation is finally catching up — sound like nothing else in the state. The output is sharper, more verbose, more politically engaged, and increasingly visible at festivals that historically locked out hip-hop entirely.",
      "## What to watch for the rest of the year",
      "Two of these artists have major-label deals stalled in legal negotiation. One is sitting on a mixtape that's been done since January. Another has a tour announcement coming any day. By Q4 the conversation about Texas rap is going to look genuinely different than it did at the start of the year. The state has been the most underrated regional scene in American rap for almost a decade. 2026 is the year that stops being true.",
      "Watch this list. We'll be updating it as the year develops.",
    ],
    tags: [
      'Texas Rap',
      'Houston',
      'San Antonio',
      'Dallas',
      'Austin',
      'Artist Roundup',
      'Don Toliver',
      'Maxo Kream',
      'Tobe Nwigwe',
      '2026',
    ],
  },
  {
    slug: 'freddie-dredd-back-to-hell-aztec-may-2026',
    type: 'review',
    title: "Freddie Dredd Brings the Back to Hell Tour to San Antonio's Aztec Theatre",
    subtitle:
      'Surprise Texas opener, four genuine sets at the intimate Aztec, and a headliner who held the room from first song to last.',
    author: 'Diego Jauregui',
    date: '2026-05-01',
    displayDate: 'May 1, 2026',
    category: 'Concert Review',
    venue: 'Aztec Theatre',
    coverIndex: 5,
    heroImage: '/articles/freddie-dredd-back-to-hell-aztec-may-2026/freddie-dredd-hero-dsc5420.png',
    readTime: '6 min read',
    body: [
      "The Back to Hell Tour made its San Antonio stop at the Aztec Theatre on May 1st, and what was already shaping up to be a great night of live music turned into something even better. The original bill listed **Germ** and one other opener alongside headliner **Freddie Dredd** — but the night came with a surprise addition in the form of a local Texas rapper who nobody saw coming. The crowd's reaction said it all. By the end of his set, fans were asking who he was, and the buzz around him carried all the way through the rest of the night.",
      "For anyone unfamiliar: Freddie Dredd has spent the last six years carving out one of the more singular lanes in modern rap. His catalog leans heavy on chopped, distorted, lo-fi production — closer in feel to the Memphis underground tradition of DJ Spanish Fly and Tommy Wright III than to anything happening on contemporary radio. He came up in close orbit with the **G*59** community and the broader **$uicideboy$** ecosystem, and his crossover to bigger rooms has been slow, quiet, and almost entirely fan-driven. The Aztec stop was the closest thing he's done to a proper Texas headline run in years.",
      "[PHOTOS:/articles/freddie-dredd-back-to-hell-aztec-may-2026/germ-1.png|Germ holds the Aztec Theatre crowd during his Back to Hell Tour set;;/articles/freddie-dredd-back-to-hell-aztec-may-2026/germ-2.png|Germ raises the mic mid-song under the Aztec Theatre's stage lights]",
      "## The room",
      "The Aztec Theatre seats about 1,800, and at capacity it's one of the more flattering rooms for rap shows in the state. The sightlines are tight, the sound system has held up well since the most recent renovation, and the balcony lets you see the entire floor without losing the energy of the pit. It's an old vaudeville house — built in 1926, restored, refurbished, and now one of the most consistently booked mid-sized rooms in San Antonio. For a tour like this one, the room is almost too dignified, and that contrast is part of why the night worked.",
      "All four performers brought something genuine to the stage. The intimate setting of the Aztec Theatre worked in everyone's favor — there's no smoke beyond the standard stage hazer, no pyrotechnics, no massive production, but there doesn't need to be. The energy in the room filled every gap. One artist jumped down from the stage into the pit mid-performance, grabbing fans' phones to record himself while the crowd lost it. Another connected with the audience between songs, taking time for real dialogue rather than just running through a setlist. The DJs held everything together seamlessly throughout the night.",
      "[PHOTOS:/articles/freddie-dredd-back-to-hell-aztec-may-2026/freddie-dredd-2.png|Freddie Dredd performs through stage smoke at the Aztec Theatre;;/articles/freddie-dredd-back-to-hell-aztec-may-2026/freddie-dredd-4.png|Freddie Dredd locked in under deep red light at the Aztec Theatre, San Antonio]",
      "## The openers",
      "**Germ** — a longtime $uicideboy$ collaborator and one of the more underrated voices in the broader G*59 catalog — handled the second-to-last slot like a veteran. His material translates better live than on record, and his half-screamed, melodic delivery cuts through the room in a way the studio mixes don't fully capture. He's been touring this material for nearly a year, and the polish is visible.",
      "[PHOTOS:/articles/freddie-dredd-back-to-hell-aztec-may-2026/germ-3.png|Germ delivers a verse close-up at the Aztec Theatre;;/articles/freddie-dredd-back-to-hell-aztec-may-2026/germ-4.png|Germ closes out his opening set on the Back to Hell Tour]",
      "## The headliner",
      "**Freddie Dredd** closed the night the way a headliner should — commanding the room and keeping the energy locked in from the first song to the last. The setlist drew heavily from the recent **Back to Hell** rollout, with a few deep cuts that triggered the crowd's biggest reactions of the night. His stage presence is understated — minimal pacing, no extended monologues, no encore theater — but the result is that the music does what the music is supposed to do. You watch a Freddie Dredd set and you remember the songs, not the show. That's a compliment.",
      "If you're a fan of **$uicideboy$** or that pocket of dark rap, this tour is worth every penny. Tickets are affordable, the shows are intimate, and the performances deliver. StagePulse recommends catching the Back to Hell Tour if it's coming to your city.",
      "[PHOTOS:/articles/freddie-dredd-back-to-hell-aztec-may-2026/freddie-dredd-1.png|Freddie Dredd commands the Aztec Theatre stage during his Back to Hell Tour headlining set;;/articles/freddie-dredd-back-to-hell-aztec-may-2026/freddie-dredd-cover.png|Freddie Dredd close-up under the Aztec Theatre's stage lights]",
    ],
    tags: [
      'Freddie Dredd',
      'Germ',
      'Aztec Theatre',
      'San Antonio',
      'Back to Hell Tour',
      'Concert Review',
      '$uicideboy$',
      'G*59',
    ],
  },
  {
    slug: 'paper-tiger-san-antonio-venue-spotlight',
    type: 'spotlight',
    title: "Inside Paper Tiger: How a 1,200-Cap Room Became San Antonio's Most Important Venue",
    subtitle:
      "On the Saint Mary's strip, a former auto shop turned music hall has quietly become the city's loudest argument that scale isn't the same as importance.",
    author: 'Diego Jauregui',
    date: '2026-04-28',
    displayDate: 'April 28, 2026',
    category: 'Venue Spotlight',
    venue: 'Paper Tiger',
    coverIndex: 5,
    readTime: '6 min read',
    body: [
      "If you've been to a show in San Antonio in the last five years, there's a real chance it happened at Paper Tiger. The 1,200-capacity venue on the Saint Mary's strip has quietly become the most important room in the city — not by size, not by marketing, but by the consistency of what they book. While the larger rooms downtown chase the touring market that can afford their overhead, Paper Tiger has built its identity around the artists who are one tour cycle away from outgrowing the room, and the result is a calendar that consistently catches acts at the exact moment they matter.",
      "## What Paper Tiger actually is",
      "A former auto shop turned music hall, opened in 2015 in the space that previously housed the long-running **White Rabbit**. Concrete floors, a stage that gets you closer to artists than almost any other room of its size in Texas, and a sightline situation that means the back of the room is still better than the middle of any arena. The capacity is exactly the right number for the artists who play it — big enough to feel like a real show, small enough to feel like a real room.",
      "There's no balcony, no VIP tier, no premium pit. The room flattens everyone in the audience into the same crowd, and that egalitarian setup is part of why artists end up referencing the venue in interviews after they play it. The bar runs along the back wall, the merch table is just past the sound booth, and on a sold-out night the only place to stand is on the floor.",
      "## The Saint Mary's strip context",
      "Paper Tiger doesn't exist in isolation. The Saint Mary's strip — the run of bars, music venues, and food spots along North Saint Mary's Street, just north of downtown — is one of the few neighborhoods in Texas where you can walk between three or four legitimate music rooms in a single night. The strip's been the home of San Antonio's underground music scene for two decades, and Paper Tiger is the current anchor.",
      "**Hi-Tones** across the street keeps the post-show crowd circulating. **The Lonesome Rose** pulls the country and Americana traffic. Smaller bars and pop-up rooms fill in the rest. The whole stretch operates more like Austin's old Red River district than the rest of San Antonio, and Paper Tiger's success has been a major reason the strip stayed viable through the rough years.",
      "## Why the booking matters",
      "Paper Tiger's calendar is consistently three steps ahead of the rest of the city. Touring acts who would absolutely have been booked at the Aztec or the Majestic a few years ago are choosing this room instead. Part of that is price — the Aztec and Majestic carry significantly higher overhead. Part of it is intimacy. Most of it is that the staff actually books with curatorial intention — they're not chasing whatever's on Billboard. The result is a calendar that overweights toward the kinds of acts that get covered in editorial places like this one rather than the ones with the biggest top-line numbers.",
      "Past Paper Tiger bookings include early-career stops from artists who have since gone on to fill amphitheaters. The room has hosted rap, indie, electronic, punk, and Latin alternative bills across the same week. The booking team has been remarkably consistent about what they say yes to — and even more disciplined about what they say no to.",
      "## What's next",
      "The summer calendar is one of the strongest the room has had. Four shows we're already credentialed for, two more we're hoping to be at, and a handful of announcements expected before July. If you're trying to understand what's actually happening in San Antonio music in 2026, Paper Tiger is where you start.",
      "Buy the merch. Tip the bartender. Get in the pit. That's the deal.",
    ],
    tags: [
      'Paper Tiger',
      'San Antonio',
      'Venue Spotlight',
      'Saint Marys Strip',
      'Live Music',
    ],
  },
  {
    slug: 'rolling-loud-california-2026-recap',
    type: 'review',
    title: 'Rolling Loud California 2026 Recap: Three Days, One Hell of a Texas Showing',
    subtitle:
      'Texas rappers held more of the lineup than anyone outside the state expected — and the crowds reacted accordingly.',
    author: 'Diego Jauregui',
    date: '2026-04-10',
    displayDate: 'April 10, 2026',
    category: 'Festival Recap',
    venue: 'Hollywood Park',
    coverIndex: 3,
    readTime: '6 min read',
    body: [
      "Rolling Loud California wrapped at Hollywood Park last weekend, and the Texas presence on the lineup was bigger than anyone outside the state was framing it as. Across three days and four stages, you could have built an entire set out of just the Texas-born acts on the bill — and most of them outdrew their slot. Rolling Loud has been the dominant rap festival on the global circuit for nearly a decade, and the California weekend has historically been weighted toward LA artists and West Coast bookings. The 2026 edition felt different from the first day.",
      "## The Texas takeover",
      "The headliner conversation didn't include any Texans this year, which is fair — the biggest names on the top of the poster were East Coast and LA artists, plus the usual run of international bookings that Rolling Loud has been pushing into the mainline since 2022. But the mid-card was a different story. Crowds reacted to the regional sets the way you'd expect a hometown reaction — even though Hollywood Park is a long way from any of the cities these artists are from.",
      "That speaks to how much Texas rap has traveled in the last twelve months. The streaming numbers were already there, but festival crowd reactions are a more honest gauge of where an artist actually sits with the audience, and the regional reactions to Texas sets this year suggest the audience knows more than the booking suggested. By the end of day two, a handful of these acts should have been programmed two tiers higher on the bill.",
      "## Who made the most of it",
      "Two specific sets are going to define how this festival gets remembered. One was a Houston veteran's mid-afternoon slot that pulled a crowd nobody saw coming — the kind of overflow situation where the people who got there early ended up trapped against the barricade for the entire set. The performance lived up to the demand. Sixty minutes, no filler, no drops in energy, and a closing run of three career singles that resolved into one of the loudest crowd singalongs of the weekend.",
      "The other was a younger artist out of Dallas whose first major festival booking turned into the kind of viral moment that doesn't usually happen until day three. The set was scheduled for a smaller stage with a fraction of the audience the main stages were pulling. By the third song, the crowd had quadrupled. By the fifth, the festival staff had to open the side gates to clear pressure. By the end, the artist was getting tagged by festival accounts that had nothing to do with the booking — the kind of organic post-set bump that genuinely moves careers.",
      "## The Texas presence beyond the bill",
      "It wasn't just the lineup. The merch booths showed Texas affiliation across half the artists with their own setups. The DJ rotations between sets included Houston-screwed remixes that have become standard at every Rolling Loud weekend over the last few years. The food trucks were a third Texas barbecue. The festival doesn't program a vendor lineup, but the vendors clearly know where the energy is.",
      "## What it means going forward",
      "Rolling Loud's California weekend has historically been weighted toward LA acts and East Coast bookings. The reweighting toward Texas this year was visible from the schedule. Whether that's a one-time programming choice or a sign of where the festival is going next is the question that matters for the rest of 2026 — and given that Rolling Loud has been mid-conversation about adding a Texas weekend for years now, the answer might be coming sooner than expected.",
      "If a Rolling Loud Texas does end up happening, the conversation about American rap festivals shifts. The state's rap scene is now generating enough output to anchor a full bill. The California weekend was a useful test case. The next move is on the festival.",
    ],
    tags: [
      'Rolling Loud',
      'California',
      'Festival Recap',
      'Texas Rap',
      'Houston',
      'Dallas',
      '2026',
    ],
  },
]

export const radarEntries: RadarEntry[] = []
